from telegram import InlineKeyboardButton


def generate_buttons(labels):
    buttons = [[InlineKeyboardButton(labels[0], callback_data=labels[0]),
                InlineKeyboardButton(labels[1], callback_data=labels[1])],
                [InlineKeyboardButton(labels[2], callback_data=labels[2]),
                InlineKeyboardButton(labels[3], callback_data=labels[3])]]
    return buttons

question = {0:"Qual'è l'unità di misura della tensione elettrica?",
            1:"Qual'è il modulo del numero complesso 4+i3 ?",
            2:"Qual'è l'unità di misura della corrente elettrica?",
            3:"Qual'è l'unità di misura della potenza?",
            4:"Qual'è la derivata di sin(x) rispetto a x?",
            5:"Sia f(x)=k1*x + k2. Qual'è la derivata di f(x) rispetto a x?",
            6:"Quanto vale il valor medio di sin(x) calcolato su un periodo?",
            7:"Qual'è l'unità di misura del campo elettrico?",
            8:"Qual'è l'unità di misura del campo magnetico?",
            9:"Qual'è l'unità di misura della frequenza?",
            10:"Come si calcola l'energia cinetica?",
            11:"Se f è una funzione lineare ed f(x1) vale 5. Quanto vale f(5 x1)?",
            12:"Sia f una funzione periodica. Il suo integrale su un periodo vale 10. Quanto vale l'integrale su tre periodi?",
            13:"20°C, espressi in kelvin, sono pari a:",
            14:"Durante la fase di evaporazione, la temperatura dell'acqua:"}
answer = {0:generate_buttons(['metri (m)', 'joule (J)', 'volt (V)', 'newton (N)']),
          1:generate_buttons(['16', '5', '9', '25']),
          2:generate_buttons(['ampere (A)', 'watt (W)', 'Farad (F)', 'weber (Wb)']),
          3:generate_buttons(['watt (W)', 'joule (J)', 'pascal (Pa)', 'kelvin (K)']),
          4:generate_buttons(['log(x)', '1/tan(x)', '-cos(x)', 'cos(x)']),
          5:generate_buttons(['k2+k1', 'k1', 'k2', 'k1*k2']),
          6:generate_buttons(['0', '1', 'infinito', '-1']),
          7:generate_buttons(['V', 'kg', 'm/V', 'V/m']),
          8:generate_buttons(['rad', 'A/m', 'm2', 'Hz']),
          9:generate_buttons(['m', 'Wb', 'Hz', '°C']),
          10:generate_buttons(['mv', '0.5 m v^2', 'm g h', 'v^2/2']),
          11:generate_buttons(['1', '5', '25', '0.5']),
          12:generate_buttons(['10', '3.3', '15', '30']),
          13:generate_buttons(['-273.15 K', '293.15 K','10000 K','-20 K']),
          14:generate_buttons(['aumenta', 'è costante', 'diminuisce', 'vale 100 K'])}
right_answer = {0:"volt (V)",
                1:"5",
                2:"ampere (A)",
                3:"watt (W)",
                4:"cos(x)",
                5:"k1",
                6:"0",
                7:"V/m",
                8:"A/m",
                9:"Hz",
                10:"0.5 m v^2",
                11:"25",
                12:"30",
                13:"293.15 K",
                14:"è costante"}